apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: quickstart-k-s
build:
  artifacts:
    - image: dockersamples/examplevotingapp_result
      context: result
    - image: dockersamples/examplevotingapp_vote
      context: vote
    - image: dockersamples/examplevotingapp_worker
      context: worker
manifests:
  rawYaml:
    - manifests/*.yaml
