apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: quickstart-k-s
build:
  artifacts:
    - image: dockersamples/examplevotingapp_result
      context: result
    - image: dockersamples/examplevotingapp_vote
      context: vote
    - image: dockersamples/examplevotingapp_worker
      context: worker
manifests:
  rawYaml:
    - manifests/db-deployment.yaml
    - manifests/db-persistentvolumeclaim.yaml
    - manifests/db-service.yaml
    - manifests/redis-deployment.yaml
    - manifests/redis-persistentvolumeclaim.yaml
    - manifests/redis-service.yaml
    - manifests/result-deployment.yaml
    - manifests/result-ingress.yaml
    - manifests/result-service.yaml
    - manifests/vote-deployment.yaml
    - manifests/vote-ingress.yaml
    - manifests/vote-service.yaml
    - manifests/worker-deployment.yaml
